# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "theevnt-spark"
  config.vm.hostname = "theevnt-spark"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 8080, host: 12345

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", type: "dhcp"

  config.vm.synced_folder "../", "/opt/theevnt-spark", type: "nfs"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

   config.vm.provision "shell", 
     inline: "
   #     puppet module install puppetlabs-apt --force
   #     puppet module install puppetlabs-stdlib --force
   #     puppet module install puppetlabs-java --force
   #     puppet module install adrien/alternatives --force
   #     puppet module install cesnet-hadoop --force
   #     puppet module install cesnet-spark --force
   #      puppet module install spantree-java8 --force
        # wget http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key -O archive.key
        # sudo apt-key add archive.key
        # sudo wget 'http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/cloudera.list' -O /etc/apt/sources.list.d/cloudera.list
        # apt-get update
     "

  config.vm.provision "puppet" do |puppet|
    puppet.options = "--verbose"
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "site.pp"

  end


end
